Footer Component
Tech4covid19/trackovid-landing-page pull request #12
Opened 2020-03-18 22:39 UTC by diogoteix

2020-03-18 23:03 UTC, ruisaraiva19 requested changes

2020-03-18 23:03 UTC, ruisaraiva19 commented on src/components/footer/index.jsx
> +import heart from "../../assets/heart.svg";
Please use the `@` alias for consistency.
```jsx
import heart from "@/assets/heart.svg";
```

2020-03-18 23:04 UTC, ruisaraiva19 commented
This PR as the #11 as a dependency.

2020-03-19 07:46 UTC, ruisaraiva19 approved these changes

2020-03-19 08:53 UTC, taniaprocha commented on src/components/footer/index.jsx
> +      <span>Made with</span>
Replace `span` by `typography`

2020-03-19 08:54 UTC, taniaprocha commented on src/components/footer/index.jsx
> +      <span>in Portugal</span>
Same 👆

2020-03-19 09:11 UTC, ruisaraiva19 approved these changes

2020-03-19 09:12 UTC, ruisaraiva19 commented on src/components/footer/index.jsx
> +      <span>Made with</span>
Updated!

2020-03-19 09:29 UTC, taniaprocha approved these changes
👍

2020-03-19 09:30 UTC, merged